---
title: "tutorial9"
author: "Madhab"
date: "2023-05-04"
output: html_document
---

<<<<<<< HEAD
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(kableExtra)
library(here)
```

```{r}
crime <- read_csv(here::here("Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019.csv"))
```
```{r}
crime %>% ggplot(aes(x = `Offence Division`)) + geom_bar()+
  labs(x= "Offence Division", y= "Frequency") + 
  ggtitle("Distribution of Offence Division")
=======
# Load libraries

```{r}

library(tidyverse)
library(ggplot2)
library(dplyr)

```


# Load dataset

```{r}

# Read the dataset
crime_data <- read.csv("Data_Tables_Criminal_Incidents_Visualisation_Year_Ending_December_2019.csv")

```

```{r}

head(crime_data)

```


# Plotting a graph

```{r}
# Filter the data to only include C Drug Offences
drug_offences <- crime_data %>% filter(Offence.Division == "C Drug offences")

# Create the line graph
ggplot(drug_offences, aes(x = Year, y = Rate.per.100.000.population)) +
  geom_col(position = "dodge") +
  ggtitle("Rate of recorded incidents for C Drug Offences") +
  xlab("Year") +
  ylab("Rate per 100,000 population")

>>>>>>> e6d5261551b4fc94423b7cee994c20684496bbfd
```

